#pragma once

// ============================================================================
//  AudioSystemViewportIcons
//
//  Registers per-component viewport icons for the AudioSystem plugin.
//
//  Icon PNG files must be placed in Content/Editor/Icons/ relative to the
//  plugin folder. The paths below document the expected icon file names. The
//  actual PNG assets are art files and are not generated by this code.
//
//  Flax Editor icon registration (C++ side):
//    The Flax C++ Editor API does not expose a direct icon-registration call
//    for actor/script components in Flax <= 1.9. The canonical approach is to
//    provide a C# editor script that calls:
//
//      Editor.Instance.Icons.AddIcon(typeof(AudioProxyComponent), iconTexture);
//
//    This class provides:
//      1. The documented icon paths (constants below).
//      2. A Register() / Unregister() stub with TODO markers for the C# side.
//      3. A helper that verifies icon files exist on disk so that missing
//         assets produce a clear error rather than a silent fallback.
//
//  TODO: Once the project has a C# editor scripts directory, create
//        AudioSystemIconsEditor.cs that calls Editor.Instance.Icons.AddIcon()
//        for each component listed here.
// ============================================================================

class AUDIOSYSTEMEDITOR_API AudioSystemViewportIcons
{
public:
    // ========================================================================
    //  Icon file paths (relative to plugin Content folder)
    // ========================================================================

    static constexpr const Char* k_IconProxy          = TEXT("Editor/Icons/AudioProxyComponent128.png");
    static constexpr const Char* k_IconListener        = TEXT("Editor/Icons/AudioListenerComponent128.png");
    static constexpr const Char* k_IconTrigger         = TEXT("Editor/Icons/AudioTriggerComponent128.png");
    static constexpr const Char* k_IconRtpc            = TEXT("Editor/Icons/AudioRtpcComponent128.png");
    static constexpr const Char* k_IconSwitchState     = TEXT("Editor/Icons/AudioSwitchStateComponent128.png");
    static constexpr const Char* k_IconBoxEnvironment  = TEXT("Editor/Icons/AudioBoxEnvironmentComponent128.png");
    static constexpr const Char* k_IconSphereEnvironment = TEXT("Editor/Icons/AudioSphereEnvironmentComponent128.png");
    static constexpr const Char* k_IconAnimation       = TEXT("Editor/Icons/AudioAnimationComponent128.png");

    // ========================================================================
    //  Lifecycle
    // ========================================================================

    /// Log expected icon paths and warn for any that are missing.
    /// Actual icon binding is handled by the C# editor script (see file note).
    static void Register();

    /// Unregister any resources associated with viewport icons.
    /// Currently a no-op — cleanup is handled on the C# side.
    static void Unregister();

private:
    AudioSystemViewportIcons() = delete;
    ~AudioSystemViewportIcons() = delete;

    /// Returns the absolute path to a plugin-relative icon path.
    static String ResolveIconPath(const Char* relativePath);

    /// Logs a warning if the icon file at \p absolutePath does not exist.
    static void ValidateIconFile(const Char* componentName, const String& absolutePath);
};
